Mucking with isert_dkms
Bro the source doesn't even compile because of a typo.

But also it appears to require old kernel stuff, just like iser_dkms
(who knew).

    /build/src/usr/src/isert-5.8/ib_isert.c: In function 'isert_handle_scsi_cmd':
    /build/src/usr/src/isert-5.8/ib_isert.c:1136:17: error: implicit declaration of function 'iscsit_set_unsoliticed_dataout'; did you mean 'iscsit_set_unsolicited_dataout'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
     1136 |                 iscsit_set_unsoliticed_dataout(cmd);
          |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                 iscsit_set_unsolicited_dataout